Feature/oauthdemo
creatubbles/ctb-api-swift pull request #116
Opened 2017-05-01 08:34 UTC by coolbnjmn

https://nomtek.atlassian.net/browse/CRI-992

Add APIClient demo + documentation

2017-05-10 08:34 UTC, mmiedlarz requested changes
Code:
- There are shared keys and passwords added to public repo.
- Some minor things

Func: 👍

2017-05-10 08:34 UTC, mmiedlarz commented on CreatubblesAPIClientDemo/DemoAPIClient.swift
> +    static let appId = "acbf03d5084f0d97159587e819e27b688a19b313b93db09c19f72ee1577b244d"
I really prefer to not put any keys in private repo. Could you force push clean version of this?

2017-05-10 08:34 UTC, mmiedlarz commented on CreatubblesAPIClientDemo/DemoAPIClient.swift
> +    //        APIClientAccessSingleton.sharedInstance.client.delegate = self
commented code

2017-05-10 08:34 UTC, mmiedlarz commented on CreatubblesAPIClientDemo/DemoWelcomeViewController.swift
> +            return String(element.characters.prefix(5)) == codeKey
```
return String(element.characters.prefix(codeKey.characters.count)
```

2017-05-10 08:34 UTC, mmiedlarz commented on Documentation/OauthDemo.md
> +# CreatubblesAPIClient Demo App
Is it linked anywhere? I don't see changes in `Readme.md`

2017-05-10 15:34 UTC, coolbnjmn commented on Documentation/OauthDemo.md
> +# CreatubblesAPIClient Demo App
Added a link in `README.md` :D

2017-05-15 08:24 UTC, mmiedlarz approved these changes
Minor change mentioned on slack

2017-05-15 08:49 UTC, merged