Improved error handling
creatubbles/ctb-api-swift pull request #44
Opened 2016-09-16 06:47 UTC by mmiedlarz

2016-09-16 06:51 UTC, mmiedlarz commented on CreatubblesAPIClient/Sources/Core/Error/APIClientError.swift
> +    static let UnknownStatus: Int = -6001
Change to public

2016-09-16 06:52 UTC, mmiedlarz commented on CreatubblesAPIClient/Sources/Core/Error/APIClientError.swift
> +public class APIClientError: ErrorType
Add URL for APIClientError documentation:
https://partners.creatubbles.com/api/#errors
http://jsonapi.org/format/#error-objects

2016-09-16 06:53 UTC, mmiedlarz commented on CreatubblesAPIClient/Sources/Core/Error/ErrorTransformer.swift
> +        if let err = errorsFromResponse(response).first
To investigate - how can we support many errors in current APIClient implementation?

2016-09-16 11:56 UTC, pleszkiewicz commented on CreatubblesAPIClient/Sources/Core/Error/APIClientError.swift
> +                              title:  "Authentication failed",
Shouldn't it be localized?

2016-09-16 11:57 UTC, pleszkiewicz commented on CreatubblesAPIClient/Sources/Core/Error/APIClientError.swift
> +                              detail: "Authentication failed. No more details are available at the moment. Please try again.")
Localization?

2016-09-16 11:58 UTC, pleszkiewicz commented on CreatubblesAPIClient/Sources/Core/Error/APIClientError.swift
> +                              detail: "Authentication failed. No more details are available at the moment. Please try again.")
Is it user-friendly to show the same text in both title and body? 
```
**Authentication failed**
Authentication failed. No more...
```

2016-09-16 11:59 UTC, pleszkiewicz commented on CreatubblesAPIClient/Sources/Core/Error/APIClientError.swift
> +                              detail: "Upload cancelled")
```
"Upload cancelled" 
"Upload cancelled"
```

Missing localizations.

2016-09-16 12:02 UTC, pleszkiewicz commented on CreatubblesAPIClient/Sources/Core/Error/APIClientError.swift
> +                              code:   "authentication-error",
Can you store this value in any variable? It is reused in other place.

2016-09-16 12:03 UTC, pleszkiewicz requested changes
Code: +1
Func: n/a

2016-09-19 09:02 UTC, mmiedlarz commented on CreatubblesAPIClient/Sources/Core/Error/APIClientError.swift
> +                              detail: "Upload cancelled")
right now we don't support any localizations in APIClient

2016-09-19 17:04 UTC, merged