Feature/cri 663 Record tests responses
creatubbles/ctb-api-swift pull request #71
Opened 2016-12-01 10:43 UTC by JakubJankowski

jira: https://nomtek.atlassian.net/browse/CRI-663

Notes: Please use the new TestConfiguration.swift file, newest version is pinned to slack's ctb-ios channel. In that file, the new `mode` enum dictates the api's working mode - `useAPI` makes the tests run the old way, `useAPIAndRecord` makes the api run the tests the old way and record responses to files in device's documents directory, and `useRecordedResponses` causes the api to read responses from recorded files.

Also please note that `suffix` String in `TestConfiguration.swift` has to be manually changed every time tests are run in the `useAPIAndRecord` mode to make sure names are unique (for example when sending a create new group request).

2016-12-06 11:05 UTC, mmiedlarz requested changes

2016-12-06 11:05 UTC, mmiedlarz commented on CreatubblesAPIClient/Sources/Core/Error/APIClientError.swift
> +        self.status = aDecoder.decodeInteger(forKey: "status")
I think, that it's better to use `!` operators here, and keep properties non-optional.

2016-12-06 11:05 UTC, mmiedlarz commented on CreatubblesAPIClientTests/TestUtils/Offline Testing/RecorderResponseHandler.swift
> +//  Created by Nomtek on 28.11.2016.
Please use proper (MIT) license header

2016-12-06 11:05 UTC, mmiedlarz commented on CreatubblesAPIClientTests/TestUtils/Offline Testing/RecorderTestSender.swift
> +@testable import CreatubblesAPIClient
Discussed via Slack

2016-12-15 11:00 UTC, DaDer commented
Code: +1
Func: +1 (sometimes on recording some tests are failing, but this issue is not related to the task)

2016-12-15 11:14 UTC, merged